aliases_11 = {
    "st.blackops2cel": "blackops2cel",
    "pick-me": "pickme",
    "pickmeism": "pickme",
    "cesspit": "cesspool",
    "maxxing": "maxing",
    "gymmaxxing": "gymmaxing",
    "gymmaxxxing": "gymmaxing",
    "gymmaxxxxing": "gymmaxing",
    "gymaxxing": "gymmaxing",
    "gymaxxxing": "gymmaxing",
    "gymaxxxxing": "gymmaxing",
    "looksmaxxing": "looksmaxing",
    "looksmaxxxing": "looksmaxing",
    "statusmaxxing": "statusmaxing",
    "statusmaxxxing": "statusmaxing",
    "statusmaxx": "statusmaxing",
    "statusmaxxx": "statusmaxing",
}

aliases_21 = {
    "st backops2cel": "blackops2cel",
    "beta buxx": "betabuxx",
    "beta cuck": "beta",
    "just white": "jbw",
    "suicide fuel": "suifuel",
    "just shower": "justshower",
    "level up": "lu",
    "level down": "ld",
    "low value": "lv",
    "low effort": "le",
    "alpha male": "alpha-male",
    "alt right": "alt-right",
    "beta orbiter": "betaorbiter",
    "cock carousel": "carousel",
    "sexual marketplace": "sm",
    "alpha widow": "aw",
    "apex fallacy": "apexfallacy",
    "nice guy": "niceguy",
    "bad boy": "badboy",
    "silver bullet": "silverbullet",
    "weed out": "weedout",
    "gray rocking": "grayrocking",
    "bread crumbing": "breadcrumbing",
    "double standard": "doublestandard",
    "relationship marketplace": "rmp",
    "shit test": "shittest"
}

aliases_31 = {
    "high value male": "hvm",
    "low value male": "lvm",
    "high value man": "hvm",
    "low value man": "lvm",
    "high value men": "hvm",
    "low value men": "lvm",
    "high value woman": "hvw",
    "low value woman": "lvw",
    "high value women": "hvw",
    "low value women": "lvw",
    "no value male": "nvm",
    "no value man": "nvm",
    "women like that": "awalt",
    "sexual market value": "smv",
    "just be white": "jbw",
    "splitting the bill": "stb",
    "split the bill": "stb",
    "average frustrated chump": "afc",
    "pick up artist": "pua",
    "men right activist": "mra",
    "demonstration high value": "dhv",
    "demonstration low value": "dlv",
    "average frustrated chump": "afc",
    "no one cares": "noc",
    "big dick energy": "bde",
    "small dick energy": "sme",
    "zero value male": "zvm",
    "red pill woman": "rpw",
    "just be yourself": "jby",
    "relationship market place": "rmp"
}

aliases_41 = {
    "enough women like that": "awalt",
    "enough women like that": "awalt",
    "lay down and rot": "ldar",
    "alpha male of group": "amog",
    "all men are rapists": "rapist",
    "not like other girls": "nlog",
    "alpha male of the group": "amog",
    "men s rights activist": "mra",
    "demonstration of high value": "dhv",
    "demonstration of low value": "dlv",
    "alpha fucs beta bucks": "afbb",
    "alpha fux beta bucx": "afbb"
}

trp_gatekeeping = {
    "bluepilled",
    "bluepill",
    "meek",
    "meeks",
    "mentalcel",
    "mentalcel",
    "awalt",
    "amog",
    "bot",
    "sjw",
    "feminist",
    "feminazi",
    "soy",
    "soyboy",
    "doublestandards",
    "knight",
    "bloop",
    "blooper",
    "twerp"
}

trp_misagony = {
    "carousel",
    "meeks",
    "meek",
    "alphawidow",
    "femcel",
    "stacy",
    "becky",
    "femoid",
    "fiona",
    "hamster",
    "roastie",
    "fuckable",
    "pussy",
    "chameleon",
    "plate"
}

trp_advanced_date_theory = {
    "frame",
    "hypergamy",
    "game",
    "pua",
    "lookism",
    "betaorbiter",
    "looksmaxing",
    "alpha",
    "beta",
    "sigma",
    "gamma",
    "dhv",
    "dlv",
    "amog",
    "afbb",
    "alphawidow",
    "apexfallacy",
    "briffault",
    "triad",
    "heightcel",
    "cuck",
    "sm",
    "friedzone",
    "misandry",
    "neg",
    "negging",
    "niceguy",
    "omega",
    "hierarchy",
    "orbiter",
    "purple",
    "wall",
    "badboy",
    "rollercoaster",
    "plates",
    "noc",
    "smv",
    "silverbullet",
    "bde",
    "plate",
    "rmp",
    "shittest",
    "solipsm"
}

blackpill_advanced_date_theory = {
    "awalt",
    "beta",
    "alpha",
    "betabuxx",
    "smv",
    "blackops2cel",
    "virgin",
    "fakecel",
    "suifuel",
    "heightcel",
    "hypergamy",
    "looksmatch",
    "meeks",
    "meek",
    "mentalcel",
    "wristcel",
    "divorcerape",
    "chad",
    "lookism",
    "betaorbiter",
    "chadfishing",
    "gymmaxing",
    "sm",
    "statusmaxing",
    "heightcel",
    "noncel",
    "volcel",
    "cuckold",
    "cuck",
    "excitement",
    "noc",
    "overvaluation",
    "smv",
    "sme"
}

bps_gatekeeping = {
    "normie",
    "roastie",
    "stacy",
    "volcel",
    "justshower",
    "fakecel",
    "mentalcel",
    "bluepill",
    "bluepilled",
    "female",
    "females",
    "femoid",
    "stacy",
    "betaorbiter",
    "halo",
    "heightcel",
    "noncel",
    "jby",
    "knight",
    "bloop",
    "blooper",
    "beta",
    "betabuxx"
}

blackpill_misogyny = {
    "femoid",
    "foid",
    "hypergamy",
    "stacy",
    "carousel",
    "dogpill",
    "landwhale"
}

blackpill_rant = {
    "kissless",
    "touchless",
    "hugless",
    "handholdless",
    "friendless",
    "virgin",
    "ldar",
    "mog",
    "ascend",
    "mra",
    "ragefuel",
    "suifuel",
    "heightcel",
    "zeta",
    "shortcel",
    "jby"
}

blackpill_cope = {
    "rope",
    "gymcel",
    "sui",
    "suicide",
    "cope",
    "lifefuel",
    "based",
    "jfl",
    "ascend",
    "wizard",
    "jby",
    "gymmaxing",
    "looksmaxing",
    "statusmaxing"
}

blackpill_racism = {
    "chad",
    "tyrone",
    "chang",
    "jamal",
    "currycel",
    "jbw",
    "chaddam",
    "chadpreet"
}

fds_advanced_date_theory = {
    "hvm",
    "lvm",
    "hvw",
    "lvw",
    "nvm",
    "zvm",
    "pickmeisha",
    "splitting",
    "stb",
    "standarts"
    "ld",
    "lu",
    "grooming",
    "groom",
    "vet",
    "vetting",
    "weedout",
    "grayrocking",
    "bde",
    "breadcrumbing",
    "sme",
    "grayrocking"
}

fds_misandry = {
    "amar",
    "rapist",
    "gaslighting",
    "gaslight",
    "scrote",
    "bde",
    "scrotation",
    "dickhead"
}

fds_gatekeeping = {
    "pickme",
    "nlog",
    "queen",
    "gaslighting",
    "gaslight",
    "vet",
    "vetting",
    "vetting"
    "groom",
    "grooming",
    "coddling",
    "mask",
    "audacity",
    "bangmaid",
    "bitch",
    "cockholm",
    "pick",
    "sme",
    "rpw"
}
